import time
import uuid
import logging
from typing import List, Optional, Dict, Any

from backend.config import settings
from backend.models import (
    CameraResponse, CameraStatus,
    CameraHealthTicket, TicketSeverity, TicketStatus
)
from backend.database import db

logger = logging.getLogger("ai_access.camera_health")

def record_camera_heartbeat(
    camera_id: str,
    status_value: CameraStatus = CameraStatus.ACTIVE,
    error_message: str = ""
) -> bool:
    """Updates camera heartbeat timestamp and health status."""
    key = f"cam:{camera_id.strip().upper()}"
    data = db.get_json(key)
    if not data:
        return False

    now = time.time()
    data["last_heartbeat"] = now
    data["status"] = status_value.value
    data["error_message"] = error_message
    db.set_json(key, data)
    return True

def monitor_and_report_health() -> Dict[str, Any]:
    """
    Scans all linked cameras.
    If a camera fails to respond or exceeds the timeout threshold (>120s),
    it flags the camera as INACTIVE/ERROR and automatically generates a maintenance ticket.
    """
    now = time.time()
    timeout_sec = settings.CAMERA_TIMEOUT_THRESHOLD_SEC
    cam_keys = db.list_keys("cam:*")

    total_checked = 0
    issues_found = 0
    generated_tickets: List[CameraHealthTicket] = []

    for k in cam_keys:
        cam_data = db.get_json(k)
        if not cam_data or not cam_data.get("is_linked", True):
            continue

        total_checked += 1
        cid = cam_data.get("camera_id")
        last_hb = cam_data.get("last_heartbeat", 0)
        time_since_hb = now - last_hb

        # If camera has not reported for > 2 minutes
        if time_since_hb > timeout_sec and cam_data.get("status") == CameraStatus.ACTIVE.value:
            issues_found += 1
            cam_data["status"] = CameraStatus.INACTIVE.value
            cam_data["error_message"] = f"Malfunction detected: No stream heartbeat for {int(time_since_hb)}s"
            db.set_json(k, cam_data)

            # Auto-generate maintenance ticket
            ticket = CameraHealthTicket(
                camera_id=cid,
                reported_at=now,
                status=TicketStatus.OPEN,
                issue=f"Camera {cid} connection lost ({int(time_since_hb)}s unresponsive)",
                severity=TicketSeverity.CRITICAL if "Front" in cam_data.get("name", "") else TicketSeverity.HIGH
            )
            db.set_json(f"ticket:{ticket.ticket_id}", ticket.model_dump())
            generated_tickets.append(ticket)
            logger.warning("Auto-reported malfunctioning camera: %s (Ticket: %s)", cid, ticket.ticket_id)

    return {
        "cameras_checked": total_checked,
        "issues_flagged": issues_found,
        "new_tickets": [t.model_dump() for t in generated_tickets],
        "timestamp": now
    }

def get_all_health_tickets(status_filter: Optional[str] = None) -> List[CameraHealthTicket]:
    """Lists maintenance tickets generated by the auto-health monitor."""
    keys = db.list_keys("ticket:*")
    tickets: List[CameraHealthTicket] = []

    for k in keys:
        data = db.get_json(k)
        if not data:
            continue
        if status_filter and data.get("status") != status_filter:
            continue
        try:
            tickets.append(CameraHealthTicket(**data))
        except Exception:
            pass

    return sorted(tickets, key=lambda t: t.reported_at, reverse=True)

def resolve_ticket(ticket_id: str) -> Optional[CameraHealthTicket]:
    """Marks a maintenance ticket as resolved and resets camera state."""
    key = f"ticket:{ticket_id}"
    data = db.get_json(key)
    if not data:
        return None

    now = time.time()
    data["status"] = TicketStatus.RESOLVED.value
    data["resolved_at"] = now
    db.set_json(key, data)

    # Re-activate camera
    cid = data.get("camera_id")
    if cid:
        record_camera_heartbeat(cid, CameraStatus.ACTIVE, "")

    return CameraHealthTicket(**data)
